PT-670: Fix file-text icon
VirtoCommerce/vc-module-quote pull request #41
Opened 2021-04-07 14:17 UTC by krankenbro

https://virtocommerce.atlassian.net/browse/PT-669

2021-04-07 15:56 UTC, eMazeika requested changes

2021-04-07 15:56 UTC, eMazeika commented on src/VirtoCommerce.QuoteModule.Web/Scripts/blades/quote-assets.js
> +    blade.headIcon = 'fa fa-file-text-o';
remove this and redundant empty line: child blade "inherit" icon from parent

2021-04-07 15:56 UTC, eMazeika commented on src/VirtoCommerce.QuoteModule.Web/Scripts/blades/quote-detail.js
> +            blade.headIcon = 'fa fa-file-text-o';
remove this and redundant empty line: child blades "inherit" icon from parent

2021-04-07 15:56 UTC, eMazeika commented on src/VirtoCommerce.QuoteModule.Web/Scripts/blades/quote-items.js
> +    blade.headIcon = 'fa fa-file-text-o';
remove this and redundant empty line: child blades "inherit" icon from parent

2021-04-08 09:04 UTC, akak1977 approved these changes

2021-04-08 09:04 UTC, eMazeika approved these changes

2021-04-08 09:06 UTC, merged